### ISSUE TITLE
AzureWebappConfigAppsettingsSet command setting only 1 property

### ISSUE THREAD

**Issue by JleruOHeP** [nuke-build/azure#20]
When you run

```
AzureWebappTasks.AzureWebappConfigAppsettingsSet(s => s
                    .SetResourceGroup("ResourceGroupName")
                    .SetName("WebAppName")
                    .SetSettings("KeyName=FooBarBaz SomeOtherSetting=2")                    
                );
```

the resulting cli command is 

`webapp config appsettings set --name WebAppName --resource-group ResourceGroupName --settings "KeyName=FooBarBaz SomeOtherSetting=2"`

Which results in only 1 app setting named KeyName with a value of "FooBarBaz SomeOtherSetting=2"

Command should not surround the value with quotes or should accept a collection of key-value pairs, potentially.

**Comment by matkoch** [comment]
@arodus `Settings`  should be of type `Dictionary<string, object>`.
